### ISSUE TITLE
项目启动报错啊

### ISSUE THREAD

**Issue by leihuazhe** [SpringForAll/spring4all-app#1]
ionic serve 启动的适合报错额，Error: Uncaught (in promise): Error: Cannot find module '../pages/tutorial/tutorial.module'.
Error: Cannot find module '../pages/tutorial/tutorial.module'.
    at http://localhost:8100/build/main.js:129:9
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14356)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4509:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14296)
    at r.run (http://localhost:8100/build/polyfills.js:3:9523)
    at http://localhost:8100/build/polyfills.js:3:19622
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15040)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4500:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14961)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10214)
    at c (http://localhost:8100/build/polyfills.js:3:19132)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:18554)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:46393:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:46381:14)
    at http://localhost:8100/build/vendor.js:46436:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14356)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4509:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14296)
    at r.run (http://localhost:8100/build/polyfills.js:3:9523)
    at http://localhost:8100/build/polyfills.js:3:19622

**Comment by huiqiangyang** [comment]
我本地没有出现这个现象的，你拉取最新代码试试了
